global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172-31-32-154:9090','172.31.39.215:9100,'172.31.39.60:9100]
